apiVersion: apps/v1
kind: Deployment
metadata:
  name: grievous-deployment
spec:
  selector:
    matchLabels:
      app: grievous
  template:
    metadata:
      labels:
        app: grievous
    spec:
      containers:
      - name: grievous
        image: mongo:6.0.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: grievous-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: grievous-secret
              key: password
