apiVersion: apps/v1
kind: Deployment
metadata:
  name: kenobi-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kenobi
  template:
    metadata:
      labels:
        app: kenobi
    spec:
      containers:
      - name: kenobi
        image: egrzeszczak/kenobi:1.0.2
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - echo
            - "hello"
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - echo
            - "hello"
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 3000
