name: Build and publish Kenobi
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-nuxt:
    name: Build and publish Kenobi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: 1. Checkout this repository

      - uses: actions/setup-node@v2
        name: 2. Prepare node environment
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: package-lock.json

      - run: npm install
        name: 3. Install dependencies (npm install)

      - run: npx nuxi build
        name: 4. Build application (npx nuxi build)

      - uses: docker/setup-qemu-action@v2
        name: 5. Set up QEMU
      
      - uses: docker/setup-buildx-action@v2
        name: 6. Set up Docker Buildx

      - uses: docker/login-action@v2
        name: 7. Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        name: 8. Get current tag

      - uses: docker/build-push-action@v3
        name: 9. Build and push to Dockerhub
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            egrzeszczak/kenobi:${{ env.RELEASE_VERSION }}
            egrzeszczak/kenobi:latest





